# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba30cdf32b02f7a09792daad4cdb5426219f4f20cccdb12ca7cf822fa9b2d914fbcca92df117bf14abcc7325364f8f62055e3dc4c3798c407bc4341504249f3

test:
  secret_key_base: 6ed2b7843bf895d5224166e46cb595dec6c985a03bc242ba9ec683495bcd29a73e07c96464cef4bec222eb35e513f8381b598fd8fa155456bea67fde751fd74f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
